spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,
    org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration"